---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: r-pipeline
  namespace: bi-dev
rules:
- apiGroups:
  - triggers.tekton.dev
  resources:
  - triggers
  - eventlisteners
  - triggerbindings
  - triggertemplates
  verbs:
  - get
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - pipelineresources
  - taskruns
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: r-pipeline-binding
  namespace: bi-dev
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: bi-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: r-pipeline

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cr-pipeline
rules:
# Permissions for every EventListener deployment to function
- apiGroups: ["triggers.tekton.dev"]
  resources: 
  - clustertriggerbindings
  - eventlisteners
  - triggerbindings
  - triggertemplates
  - triggers
  verbs: 
  - get
  - list
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - pipelineresources
  - taskruns
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-clusterRole-binding
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: bi-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-pipeline

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: test-listener
  namespace: bi-dev
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: gitea-pipeline-clusterbinding
      kind: ClusterTriggerBinding
    template:
      ref: stockbffnode
