apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: test-listener
  namespace: dev-bi
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: gitea-pipeline-clusterbinding
      kind: ClusterTriggerBinding
    template:
      ref: test

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: r-pipeline
  namespace: dev-bi
rules:
- apiGroups:
  - triggers.tekton.dev
  resources:
  - eventlisteners
  - triggerbindings
  - triggertemplates
  verbs:
  - get
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - pipelineresources
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: r-pipeline-binding
  namespace: dev-bi
subjects:
  - kind: ServiceAccount
    name: pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: r-pipeline

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cr-pipeline
rules:
# Permissions for every EventListener deployment to function
- apiGroups: ["triggers.tekton.dev"]
  resources: ["clustertriggerbindings"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-clusterRole-binding
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: dev-bi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-pipeline