---

- name: Fetch Che command line tool
  get_url:
    url: https://www.eclipse.org/che/chectl/
    dest: /tmp/install.sh
    mode: 0775

- name: Install Che Command line tool
  command: /tmp/install.sh
  become: true

- name: Install Che
  command: chectl server:deploy --platform minikube

- name: Patch Che to allow multipe workspaces
  community.kubernetes.k8s:
    state: present
    definition:
      api_version: org.eclipse.che/v1
      kind: CheCluster
      metadata:
        name: eclipse-che
        namespace: che
      spec: 
        server: 
          customCheProperties: 
            CHE_LIMITS_USER_WORKSPACE_RUN_COUNT: "-1"
