---

- name: Expand templated files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0777
  with_items:
      - {src: '{{ home }}/Cn-Tk/ibm-garage-iteration-zero/terraform/stages-minikube/stage2-argocd.tf.j2', 
        dest: '{{ home }}/Cn-Tk/ibm-garage-iteration-zero/terraform/stages-minikube/stage2-argocd.tf'}
      - {src: '{{ home }}/Cn-Tk/ibm-garage-iteration-zero/terraform/stages-minikube/stage2-dashboard.tf.j2', 
        dest: '{{ home }}/Cn-Tk/ibm-garage-iteration-zero/terraform/stages-minikube/stage2-dashboard.tf'}
      - {src: '{{ home }}/Cn-Tk/ibm-garage-iteration-zero/terraform/stages-minikube/stage2-jenkins.tf.j2', 
        dest: '{{ home }}/Cn-Tk/ibm-garage-iteration-zero/terraform/stages-minikube/stage2-jenkins.tf'}

- name: Add tls CA cert for Cloud Native Toolkit resources
  command: kubectl create secret generic tls-ca -n default --from-file=${HOME}/.minikube/certs/rootCA_crt.pem
  ignore_errors: true

- name: Patch CA cert secret so it gets copied into tool namespace
  command: kubectl patch secret tls-ca -n default -p '{"metadata":{"labels":{"grouping":"garage-cloud-native-toolkit"}}}'

- name: Add ingress secret
  command: kubectl create secret tls {{ secretName }} -n default --cert={{ home }}/.minikube/certs/ingress_crt.pem --key={{ home }}/.minikube/certs/ingress_key_nopass.pem
  ignore_errors: true

- name: Patch ingress secret so it gets copied into tool namespace
  command: kubectl patch secret {{ secretName }} -n default -p '{"metadata":{"labels":{"grouping":"garage-cloud-native-toolkit"}}}'

- name: Pull the install image
  community.general.docker_image:
    name: quay.io/ibmgaragecloud/cli-tools:v0.9.0-lite
    source: pull

- name: Ensure no previous docker container exists
  community.general.docker_container:
    name: CNTK-installer
    container_default_behavior: no_defaults
    force_kill: yes
    state: absent

- name: Deploy rest of the Cloud Native Toolkit
  community.general.docker_container:
    name: cntk-installer
    image: quay.io/ibmgaragecloud/cli-tools:v0.10.0-lite
    container_default_behavior: no_defaults
    interactive: yes
    tty: yes
    detach: no
    debug: yes
    log_driver: json-file
    output_logs: yes
    cleanup: yes
    env:
      TF_VAR_ibmcloud_api_key: ""
      TF_VAR_login_user: ""
      TF_VAR_login_password: ""
      TF_VAR_login_token: ""
      TF_VAR_source_control_url: "https://gitea.{{ minikubeIP }}.nip.io/"
      TF_VAR_server_url: "https://{{ minikubeIP }}:8443"
      TF_VAR_ingress_hostname: "{{ minikubeIP }}.nip.io"
      IBMCLOUD_API_KEY: ""
      IAAS_CLASSIC_USERNAME: ""
      IAAS_CLASSIC_API_KEY: ""
    volumes:
      - "{{ home }}/Cn-Tk/ibm-garage-iteration-zero/terraform:/home/devops/src"
      - "{{ home }}/.kube/config:/home/devops/.kube/config"
      - "{{ home }}/.minikube:/home/devops/.minikube"
    working_dir: /home/devops/src
    command: "/home/devops/src/runTerraform.sh -k -a"

- name: Fixup Gitea link in Dashboard
  community.kubernetes.k8s:
    state: present
    merge_type: strategic-merge
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: sourcecontrol-config
        namespace: tools
      data:
        SOURCECONTROL_URL: 'https://gitea.{{ minikubeIP }}.nip.io/'

- name: Add Tekton to Developer Dashboard
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: tekton-config
        namespace: tools
        labels:
          app.kubernetes.io/component: tools
          app.kubernetes.io/name: tekton-config
          app.kubernetes.io/part-of: catalyst
          group: catalyst-tools
        annotations:
          description: >-
            Config map to hold the url for tekton in the environment so that other
            tools can access it
      data:
        TEKTON_URL: 'https://tekton-dashboard.{{ minikubeIP }}.nip.io/'
